---
title: "Bus Locations in Auckland"
resource_files:
- .Renviron
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)

# source in the API helpers
source("at_api.R")


# retrieve API key from environment variable
api_key <- reactive({
  key <- get_api_key()
  
  shiny::validate(
    need(key != "", "No API key found. Set environment variable 'OCP_APIM_SUBSCRIPTION_KEY' in your .Renviron file.")
  )
  
  key
})

# retrieve data from API
d_bus_locations <- reactive({
  # run this function every few seconds
  invalidateLater(1000 * 5)
  
  # return API response
  cat("Hitting API...\n")
  get_bus_locations(api_key())
})

# retrieve number of buses
n_buses <- reactive(
  nrow(d_bus_locations())
)

# retrieve number of routes
n_routes <- reactive(
  d_bus_locations() %>% distinct(route_id) %>% nrow()
)

# load lookup table for bus routes
d_bus_routes <- reactive(get_bus_routes(api_key()))

```


Column {data-width=400}
-----------------------------------------------------------------------

### Current bus locations in Auckland

```{r}
# render empty map
output$map <- renderLeaflet({
  leaflet(options = leafletOptions(preferCanvas = TRUE)) %>% 
    addProviderTiles(providers$Hydda) %>% 
    setView(lng = 174.762224, lat = -36.846841, zoom = 12)
})

# update map whenever new data becomes available
observe({
  req(d_bus_locations())

  # join the route data to the dataframe of bus locations
  d <- d_bus_locations() %>% 
    left_join(d_bus_routes(), by = "route_id") %>% 
    mutate(
      popup = sprintf("<strong>Line %s</strong> <em>(%s)</em><p>%s</p>", route_short_name, agency_id, route_long_name)
    )
  
  discrete_pal <- colorFactor(terrain.colors(n_distinct(d$agency_id)), d$agency_id)

  # update the map
  leafletProxy("map", data = d) %>% 
    clearMarkers() %>% 
    addCircleMarkers(
      lng = ~longitude, lat = ~latitude, popup = ~popup, fillColor = ~discrete_pal(agency_id), 
      radius = 5, fillOpacity = 1, opacity = 1, color = "#000000", weight = 1
    )
    # addMarkers(lng = ~longitude, lat = ~latitude, popup = ~popup)
})

leafletOutput("map")
```


Column {data-width=150}
-----------------------------------------------------------------------

### Buses in service

```{r}
renderValueBox({
  valueBox(prettyNum(n_buses(), big.mark = ","), caption = "buses in service", icon = "fa-bus")
})
```

### Active bus routes

```{r}
renderValueBox({
  valueBox(prettyNum(n_routes(), big.mark = ","), caption = "bus routes served", icon = "fa-map-marked")
})
```
